"""Add restaurant model and relationships

Revision ID: 53acbd2d0f4f
Revises: 5a8893f78f5d
Create Date: 2025-08-07 15:35:39.726995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53acbd2d0f4f'
down_revision = '5a8893f78f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'restaurant', ['restaurant_id'], ['id'])

    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.alter_column('restaurant_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('shivdhaba_order', schema=None) as batch_op:
        batch_op.alter_column('restaurant_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'restaurant', ['restaurant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shivdhaba_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('restaurant_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.alter_column('restaurant_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
