"""Add delivered field to ShivdhabaOrder

Revision ID: c1126c923562
Revises: cf8ca12022f7
Create Date: 2025-08-02 02:26:29.016915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1126c923562'
down_revision = 'cf8ca12022f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shivdhaba_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivered', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shivdhaba_order', schema=None) as batch_op:
        batch_op.drop_column('delivered')

    # ### end Alembic commands ###
