"""Add ShivdhabaOrder table

Revision ID: cf8ca12022f7
Revises: 39e8d7b9b7b8
Create Date: 2025-07-29 20:57:26.844596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8ca12022f7'
down_revision = '39e8d7b9b7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shivdhaba_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('items', sa.Text(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shivdhaba_order')
    # ### end Alembic commands ###
